- hosts: all
  remote_user: root
  tasks:
    - name: Stop the Docker container
      docker_container:
        name: websiteapp-container
        state: stopped

    - name: Remove the Docker container
      docker_container:
        name: websiteapp-container
        state: absent

    - name: Remove the old Docker image
      docker_image:
        name: websiteapp:latest
        state: absent

    - name: Building Docker image
      docker_image:
        name: websiteapp:latest
        source: build
        build:
          path: ~/project/ansible-jenkins-pipeline/
        state: present

    - name: Creating the container
      docker_container:
        name: websiteapp-container
        image: websiteapp:latest
        ports:
          - "80:80"
        state: started

